;(set-frame-font "Pragmata")
(set-face-font `default "-apple-pragmata-medium-r-normal--0-0-0-0-m-0-iso10646-1")
;; ;(defun mynewframe ()
;; ;(set-default-font "Purisa");)
;; ;'(before-make-frame-hook mynewframe)
;; ;'(after-make-frame-functions (mynewframe))
;; ;;'(set-face-font default -unknown-Purisa-light-normal-normal-*-*-*-*-*-*-0-iso10646-1)
