;; ;; (add-to-list 'load-path "~/elisp/ecb")
;; ;; (load-file "~/elisp/cedet/common/cedet.el")
;; ;; (require 'ecb)
;; ;; (require 'semantic-util)
;; ;; (require 'semantic-load)
;; ;; (setq ecb-tip-of-the-day nil)
;; ;; (setq semantic-load-turn-useful-things-on t)
;; ;; (setq ecb-primary-secondary-mouse-buttons (quote mouse-1--mouse-2))
;; ;; (setq ecb-tip-of-the-day nil)
;; ;; (setq ecb-tree-buffer-style (quote image))
;; ;; (setq ecb-tree-indent 4)
;; ;; (setq ecb-windows-height 0.5)
;; ;; (setq ecb-windows-width 0.15)
;; ;; (setq semantic-load-turn-useful-things-on t)
;; ;; (setq semantic-load-turn-everything-on t)
